package com.antigravity.sales.queue.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Entity
@Table(name = "google_forms_config")
@Data
@NoArgsConstructor
public class GoogleFormsConfig {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // Tenant / Client identifier
    @Column(nullable = false, unique = true)
    private UUID clientId;

    // A unique token generated by our backend that the user must include in their Google App Script payload
    @Column(nullable = false, unique = true)
    private String webhookToken;
    
    private String formName;
    
    private boolean active = true;
}
